# Generated by Django 5.1.4 on 2025-01-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
